const plants = [
    {
        id: 1,
        title: 'Anthurium Clarinervum' ,
        category: 'rare',
        price: 120,
        img:'./assets/Anthurium.jpg',
        desc:'Anthurium',

    },
    {
        id: 2,
        title: 'Philodendron Verrucosum' ,
        category: 'rare',
        price:  390,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Philodendron Verrucosum',
    },
    {
        id: 3,
        title: 'Alokzacja Frydek Velvet' ,
        category: 'rare',
        price: 360,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Alokzacja Frydek Velvet',
    },
    {
        id: 4,
        title: 'Alokazja Black Velvet' ,
        category: 'rare',
        price: 210,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Alokazja Black Velvet',
    },
    {
        id: 5,
        title: 'Alokazja Azlani' ,
        category: 'rare',
        price: 480,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Alokazja Azlani',
    },
    {
        id: 6,
        title: 'Alocasia Macrorrizos Black Stem' ,
        category: 'rare',
        price: 280,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Alocasia Macrorrizos Black Stem',
    },
    {
        id: 7,
        title: 'Monstera Deliciosa Alba Variegata',
        category: 'rare',
        price: 890,
        img:'../assets/Philodendron_Verrucosum.jpg' ,
        desc: 'Monstera Deliciosa Alba Variegata',
    },
    {
        id: 8,
        title: 'Alocasia Zebrina Black',
        category: 'rare',
        price: 250,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Alocasia Zebrina Black',
    },
    {
        id: 9,
        title: 'Maranta Lemon Lime',
        category: 'rare',
        price: 380 ,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Maranta Lemon Lime',
    },
    {
        id: 10,
        title: 'Philodendron Red Beauty XXL',
        category: 'rare',
        price: 260,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc:'Philodendron Red Beauty XXL' ,
    },
    {
        id: 11,
        title: 'Euphorbia Ingens Variegata',
        category: 'rare',
        price: 2200,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Euphorbia Ingens Variegata',
    },
    {
        id: 12,
        title: 'Philodendron Ghost Green',
        category: 'rare',
        price: 230,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Philodendron Ghost Green',
    },
    {
        id: 13,
        title: 'Syngonium Variegata Emerald Gem',
        category: 'rare',
        price: 350,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Syngonium Variegata Emerald Gem',
    },
    {
        id: 14,
        title: 'Philodendron Prince Of Orange Light',
        category: 'rare',
        price: 250,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Philodendron Prince Of Orange Light',
    },
    {
        id: 15,
        title: 'Syngonium Mottled Mojito',
        category: 'rare',
        price: 190,
        img: '../assets/Philodendron_Verrucosum.jpg',
        desc: 'Syngonium Mottled Mojito' ,
    },
    

]


export default plants