const plants = [
    {
        id: 1,
        title: 'Anthurium Clarinervum' ,
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 2,
        title: 'Philodendron Verrucosum' ,
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 3,
        title: 'Alokzacja Frydek Velvet' ,
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 4,
        title: 'Alokazja Black Velvet' ,
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 5,
        title: 'Alokazja Azlani' ,
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 6,
        title: 'Alokazja ' ,
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 7,
        title: 'Monstera Deliciosa Alba Variegata',
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 8,
        title: 'Alocasia Zebrina Black',
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 9,
        title: 'Maranta Lemon Lime',
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 10,
        title: 'Philodendron Red Beauty XXL',
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 11,
        title: 'Euphorbia Ingens Variegata',
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 12,
        title: 'Philodendron Ghost Green',
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 13,
        title: 'Syngonium Variegata Emerald Gem',
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    {
        id: 14,
        title: 'Philodendron Prince Of Orange Light',
        category: 'rare',
        price: ,
        img: ,
        desc: ,
    },
    

]